[package]
name = "selectia-tauri-dto"
version = "0.1.0"
edition = "2021"

[dependencies]
ts-rs = {version = "10.0.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
selectia = { path = "../../crates/selectia" }
derive_more = { version = "1.0", features = ["full"] }