[package]
name = "theater-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
eyre = "0.6"
proc-macro-error = { version = "1", default-features = false }
