[workspace]
resolver = "2"

members = ["packages/selectia-app/src-tauri", "crates/selectia", "crates/selectia-audio-file", "crates/selectia-audio-server", "crates/selectia-tauri", "crates/selectia-tauri-dto"]
