[package]
name = "macromamba"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
tracing-subscriber = "0.3"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
eyre = "0.6"
reqwest = "0.12"
futures = "0.3"