[package]
name = "selectia-audio-file"
version = "0.1.0"
edition = "2021"

[dependencies]
symphonia = "0.5.4"
thiserror = "2"
tracing = "0.1"
dasp = { version = "0.11.0", features = ["all"] }
aubio-rs = "0.2"
# hound = {path = "../../../hound"}
hound = "3.5.0"
fundsp = "0.20.0"